export const ADD_TO_NOTIFICATION = 'ADD_TO_NOTIFICATION';
export const REMOVE_FROM_NOTIFICATION = 'REMOVE_FROM_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const LOAD_CURRENT_NOTIFICATION = 'LOAD_CURRENT_NOTIFICATION';