export const GET_RUNNERBYID_REQUEST = "GET_RUNNERBYID_REQUEST";
export const GET_ALL_RUNNERS_REQUEST= "GET_ALL_RUNNERS_REQUEST";
export const ADD_EVENT_TO_RUNNER= "ADD_EVENT_TO_RUNNER";
export const REMOVE_RUNNER_REQUEST = "REMOVE_RUNNER_REQUEST";




