export const CREATE_RUNGROUP = "ADD_TO_RUNGROUP";
export const ADD_EVENT_TO_RUNGROUP = "ADD_EVENT_TO_RUNGROUP";
export const ADD_RUNNER_TO_RUNGROUP = "ADD_RUNNER_TO_RUNGROUP";
export const DELETE_RUNGROUP = "REMOVE_FROM_RUNGROUP";
export const GET_RUNGROUP_BY_ID = "GET_RUNGROUP_BY_ID";
export const GET_ALL_RUNGROUPS = "GET_ALL_RUNGROUPS";
