export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const REMOVE_EVENT_REQUEST = "REMOVE_EVENT_REQUEST";
export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
